//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionPjct
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SessionDBEntities : DbContext
    {
        public SessionDBEntities()
            : base("name=SessionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PaymentStatu> PaymentStatus { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<sessionstatu> sessionstatus { get; set; }
        public virtual DbSet<SessionTrxn> SessionTrxns { get; set; }
    }
}
