//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionPjct
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionTrxn
    {
        public int SessionTrnId { get; set; }
        public int SessionId { get; set; }
        public int MentorId { get; set; }
        public int CandidateId { get; set; }
        public int SessionStatus { get; set; }
        public int PaymentStatus { get; set; }
        public Nullable<int> SessionCount { get; set; }
    }
}
