//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionPjct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int SessionId { get; set; }
        public string SessionName { get; set; }
        public System.DateTime SessionDate { get; set; }
        public int SessionStart { get; set; }
        public int SessionEnd { get; set; }
        public decimal SessionAmount { get; set; }
        public Nullable<int> SessionCount { get; set; }
    }
}
